### ISSUE TITLE
Could you share the code of data preprocessing?

### ISSUE THREAD

**Issue by TeresaTsang** [ldzhangyx/music-melody-segmentation-using-neural-CRF#1]
Could you share the code of data preprocessing or preprocessed pickle file like "essen_linear.pkl"? Thanks!

**Comment by ldzhangyx** [comment]
Hi, I recommend you preprocess the dataset using the MusPy package. It is easy to use.
https://github.com/salu133445/muspy

**Comment by TeresaTsang** [comment]
> Hi, I recommend you preprocess the dataset using the MusPy package. It is easy to use.
> https://github.com/salu133445/muspy

Thanks!
